### ISSUE TITLE
When a subgraph, with a Mixer node in it, is collapsed, the Mixer node stops functioning

### ISSUE THREAD

**Issue by zduturan** [nodos-dev/workspace#18]
Reality 5.4.sp2.b805

Reproduction:
- Add AjaIn and AjaOut nodes.
- Add Mixer node.
- Connect AjaIn => channel1 of Mixer node => AjaOut
- Select AjaIn and Mixer nodes, and from the menu, select "Collapse into graph"
- **Expected result**: Nothing changes in the output video.
- **Actual result**: the output video _disappears_.
- Expand the graph, and the output video comes back.

Screen recording: 
https://github.com/user-attachments/assets/7b8ce933-1598-40ed-a9ed-fbfd098a7a56

Jira: R5-774

**Comment by shamilatesoglu** [comment]
The Mixer node decides which textures to bind using pin connections. With `nos.sys.vulkan` version 5.9, we added a `"IsStockTexture"` function to the API. Instead of using `OnPinConnected/Disconnected` node callbacks, this should be used to check whether the input texture is connected. That should fix the problem.

**Comment by zduturan** [comment]
Thanks, we will implement as advised.
